<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ipv6ProvinceStatistics.Domain\Ipv6ProvinceStatistics.Domain.csproj" />
    <ProjectReference Include="..\Ipv6ProvinceStatistics.Application\Ipv6ProvinceStatistics.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\..\..\assets\templates\Ipv6ReportTemplate.xlsx" LogicalName="Ipv6ProvinceStatistics.Template.xlsx" />
    <EmbeddedResource Include="..\..\..\..\assets\templates\Ipv6ReportTemplate.sha256" LogicalName="Ipv6ProvinceStatistics.Template.sha256" />
  </ItemGroup>
</Project>
